### ISSUE TITLE
Should we remove extensions marked at risk?

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-extensions#103]
Some of these extensions are probably not implemented and there is no clear path forward.
It would be good to either remove them or move them to a dedicated section.
This way, the document would be clearer about what is being actively pursued and what is being abandoned.

**Comment by aboba** [comment]
Extensions that were removed from WEBRTC-PC due to lack of implementation, and have not been implemented since, are now collected in their own section. Since this specification is a "holding pen" anyway, there is no need to remove them, they just will never be incorporated into WebRTC-PC unless they are implemented.

**Comment by alvestrand** [comment]
I think we should move in the opposite direction, and move the stuff that has implementations into webrtc-pc, once we have agreement on what type of markup to use for "stuff that isn't at REC-level yet".
