### ISSUE TITLE
Suggestion: rename [[HeaderExtensionsToOffer]] to [[HeaderExtensionsSupported]]

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-extensions#132]
[[HeaderExtensionsToOffer]] also influences creation of answers, and also cannot force an extension to be put in a reoffer if the previous answer did not have that extension, so having "ToOffer" in its name is a bit of a misnomer.

Also, it probably makes sense to rename the other stuff (eg; setOfferedRtpHeaderExtensions to setSupportedHeaderExtensions), since that is in effect what JS is trying to do.

**Comment by alvestrand** [comment]
Agree that [[HeaderExtensionsToOffer]] needs to be [[HeaderExtensionsSupported]], since it includes the currently "stopped" extensions.
We could define the "header extensions to offer" as the set of header extensions in [[HeaderExtensionsSupported]] that are not currently "stopped" for better language flow. However, "setOfferedRtpHeaderExtensions" does, to my mind, do exactly what it says on the label.

**Comment by docfaraday** [comment]
setOfferedRtpHeaderExtensions strongly influences what we put in both offers and answers, but does not outright dictate what we use. I would argue that it does not do what it says on the tin, with that name. What it does is set the supported RTP extensions. From there, JSEP says we offer the supported RTP extensions minus anything that was not present in the previous answer, and JSEP says we answer with the intersection of the supported RTP extensions and what was present in the offer.

**Comment by alvestrand** [comment]
Hm. I think we're using "supported" in two different fashions here. I was thinking "supported" as "supported in code" - that is, as a synonym for "implemented". I think your use of "supported" is more like "negotiated for use on this transport".

(It's a side effect of the Unified Plan decision that headers are negotiated per media session, but the result has to be consistent across all media sections bundled to a single transport.)

**Comment by alvestrand** [comment]
Perhaps the internal slot is [[HeaderExtensionTargetState]]?
And we could say that setRemoteDescription() flipped the direction of every member that's not present in the remote description to "stopped"?

**Comment by docfaraday** [comment]
I am basing my definition of "supported" on the fact that we will need to define the phrase "supported RTP header extension" in JSEP in terms of this API, if we want to avoid modifying JSEP itself. Generally, over in IETF land, "supported" means "ready and _willing_", so this isn't an unexpected use of terminology.

**Comment by alvestrand** [comment]
Hm. I can't remember seeing a case where an RFC specified behavior for the case where some party is able to do something, but just refuses to do it at the moment (code supports it, but is not willing to do it).
The common writing style (citing RFC 9000 as an example) seems to assume that if you're able to do something, you're also willing to do it.

**Comment by fippo** [comment]
We do extend JSEP already [here](https://w3c.github.io/webrtc-extensions/#modifications-to-existing-procedures-0)

The naming is confusing indeed.

* getRtpHeaderExtensionsSupported() which returns a sequence of RTCRtpHeaderExtensionCapability. I have doubts this is the right model since it duplicates RTCRtpSender.getCapabilities (and the Receiver) while extending the data provided by stopped extensions. I'd prefer a [getCapabilities()](https://github.com/w3c/webrtc-extensions/issues/100#issuecomment-1110005582).headerExtensions
* setRtpHeaderExtensions(headerExtensionsToNegotiate) to set what gets negotiated in an offer/answer.
* headerExtensionsNegotiated() which lets you discover what was negotiated. IMO that is just a nice accessor for the `m=` section associated with the transceiver and extracting the information from the extmap so I have a slight preference to remove this.

**Comment by bdrtc** [comment]
some support @fippo‘s opinion, 

1. both `setRtpHeaderExtensionsSupported `or `setRtpHeaderExtensions `describe the local rtpHeaderExtension capabilities,  only that `setRtpHeaderExtensionsSupported` maybe too long.
2. `getHeaderExtensionsNegotiated` change to `getRtpHeaderExtensionsNegotiated` maybe more suitable, which describe the final RtpHeaderExtensions negotiate result.

**Comment by henbos** [comment]
Completed as part of https://github.com/w3c/webrtc-extensions/pull/142
