### ISSUE TITLE
RTP Header Extension Encryption

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-extensions#47]
Justin Uberti did a presentation in AVTCORE today about the status of RTP Header Extension support in WebRTC:
https://www.ietf.org/proceedings/108/slides/slides-108-avtcore-rtp-header-extension-encryption-full-01

Current WebRTC implementations (both browsers and SFUs) do not support the negotiation envisaged in RFC 6904, which appears too complex to implement properly. The result has been leaking of RTP header extensions including audio levels), due to bugs in libsrtp and libwebrtc that remained undetected for years. 

This has lead to discussions of how we can make RTP header extension encryption deployable from a protocol and API standpoint.  With respect to APIs, two approaches have been suggested:

1. Add an argument to `setOfferedRtpHeaderExtensions` to indicate whether all the extensions should be encrypted (the default) or not.
2. Add a member to `RTCConfiguration`: 'negotiate' or 'require'

**Comment by lgrahl** [comment]
I'd prefer the former. The one thing I believe is really important is that we do have the two options:

* `negotiate` (default) which indicates that it will try to negotiate encryption for all header extensions and silently fall back to sending and receiving non-encrypted header extensions in case it couldn't negotiate encryption for them.
  From a technical perspective, something like `a=encrypted-hdrs:optional` would be sent from the local side and if the remote side sends either `a=encrypted-hdrs:optional` or `a=encrypted-hdrs:required`, **both encrypt. Otherwise, they both send the extensions in plaintext.**
* `require` which indicates that it will only send encrypted header extensions or none at all.
  From a technical perspective, something like `a=encrypted-hdrs:required` would be sent from the local side and if the remote side sends either `a=encrypted-hdrs:optional` or `a=encrypted-hdrs:required`, **both encrypt. Otherwise, neither side sends any header extensions.**

(Side note: I guess I kinda have suggested a negotiation logic by describing how I think it could work now. So, /cc @juberti)

**Comment by juberti** [comment]
I think it can be even simpler, you always include a=extmap-encrypted, and 'require' means that you explode if the other side doesn't support a=extmap-encrypted. (Not sending extensions at all seems like a suboptimal failure mode.)

This is similar to what we had proposed for a=rtcp-mux before that was made mandatory.

**Comment by lgrahl** [comment]
Yep, that sounds better. :+1: Edited my post accordingly.

**Comment by juberti** [comment]
I'm not sure we want to extend `setOfferedRtpHeaderExtensions`, because we're talking about encrypting more than just extensions. I'd suggest a new member, e.g., `rtpHeaderEncryptionPolicy`.

Regarding the difference between
1.  `RtpTransceiver.rtpHeaderEncryptionPolicy` and 
2. `RTCConfiguration.rtpHeaderEncryptionPolicy`

the main difference is that 1) needs to be done for every transceiver, which while providing more control, is easier to get wrong.

**Comment by lgrahl** [comment]
> the main difference is that 1) needs to be done for every transceiver, which while providing more control, is easier to get wrong.

Agree. There would have to be a compelling use case to not apply a global (peer connection wide) policy.
That being said, since `negotiate` is the default, the impact isn't as severe as it is today since it still will attempt to negotiate encryption.

**Comment by murillo128** [comment]
Agree, the per transceiver configuration seems an overkill.

We need to decide also what do we do with the `encrypted` attribute of the `RTCRtpHeaderExtensionParameters` : 
https://www.w3.org/TR/webrtc/#dom-rtcrtpheaderextensionparameters-encrypted

which doesn't make sense anymore of not using rfc 6904 and a global `rtpHeaderEncryptionEnabled`  boolean flag in the PC would make more sense.

**Comment by juberti** [comment]
One question is whether a=extmap-encrypted is available at media-level, or just session-level. If at media-level, then the `rtpHeaderEncryptionEnabled` getter would have to be per-transceiver.

Do we have any precedent for such getters?

**Comment by henbos** [comment]
I'll make slides for the virtual interim

**Comment by aboba** [comment]
Virtual interim slides are [here](https://docs.google.com/presentation/d/14Bzs1ia23Q5yGcuPLiQnHvkjjFi9ypXgPue94Q65UIQ/edit#slide=id.g9228bfd0b2_3_21). 

IETF cryptex specification is [here](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-cryptex).

**Comment by aboba** [comment]
["Completely Encrypting RTP Header Extensions and Contributing Sources"](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-cryptex) has completed WGLC and is now in state "AD Review". 

The basics of an API proposal were discussed [here](https://docs.google.com/presentation/d/14Bzs1ia23Q5yGcuPLiQnHvkjjFi9ypXgPue94Q65UIQ/edit#slide=id.g9228bfd0b2_3_21). 

- All-or-nothing encryption.
- Encrypt RTP headers on all m= sections or none of them.
- Always attempt to negotiate it.
- Add RTCConfiguration.rtpHeaderEncryptionPolicy
  - "negotiate": If other endpoint doesn’t support it, send unencrypted.
  - "require": If the other endpoint doesn’t support it, fail to negotiate (throw an exception on setRemoteDescription).
- Add RTCRtpTransceiver.encryptionNegotiated flag.

**Comment by alvestrand** [comment]
Is the extension marked as "bundle:TRANSPORT" or "bundle:IDENTICAL"?

**Comment by aboba** [comment]
Henrik's slides seem to suggest IDENTICAL, but 
[draft-ietf-avtcore-cryptex Section 4](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-cryptex#section-4) says: 

  "When used with BUNDLE, this attribute is assigned to the TRANSPORT
   category [RFC8859].  If BUNDLE is in use and the a=cryptex attribute
   is present for a media line, it MUST be present for all media lines
   belonging to the same bundle group.  This ensures that the encrypted
   MID header extensions used to demux BUNDLE can be processed
   correctly."

**Comment by aboba** [comment]
Based on draft-ietf-avtcore-cryptex, it seems like it works as follows: 

- An Offer or Answer from a browser supporting cryptex contains `a=cryptex` on all m-lines, indicating the ability to receive Encrypted Header Extensions.
- On the Offerer, `RTCRtpTransceiver.encryptionNegotiated` is set to "true" for those m-lines where the Answerer responded with `a=cryptex`.  For these m-lines, the Offerer will send Encrypted Header Extensions. 
- On the Answerer, `RTCRtpTransceiver.encryptionNegotiated` is set to "true" for those m-lines where the Offerer Offered `a=cryptex`. For these m-lines, the Answerer will send Encrypted Header Extensions. 
- If `RTCConfiguration.rtpHeaderEncryptionPolicy` = "require" on an Offerer, then it will expect `a=cryptex` on all m-lines in the Answer.  If not, negotiation will fail. 
- If `RTCConfiguration.rtpHeaderEncryptionPolicy` = "require" on an Answerer, then it will expect `a=cryptex` on all m-lines in the Offer.  If not, negotiation will fail.
- If `RTCConfiguration.rtpHeaderEncryptionPolicy` = "negotiate" on an Offerer, then it will expect an Answer with `a=cryptex` present on all m-lines within a BUNDLE, or on no -lines within a BUNDLE. If not, negotiation will fail. 
- If `RTCConfiguration.rtpHeaderEncryptionPolicy` = "negotiate" on an Answerer, then it will expect an Offer with `a=cryptex` present on all m-lines within a BUNDLE, or on no -lines within a BUNDLE. If not, negotiation will fail.

**Comment by alvestrand** [comment]
The question of bundling is really how we need to deal with offers coming from non-browsers.
If draft-ietf-avtcore-cryptex stays the way it is, we must have a sensible code path for dealing with SDP containing:

a=group:BUNDLE A B
a=group:BUNDLE C D

m=audio
a=cryptex
a=mid:A
m=audio
a=cryptex
a=mid:B

m=video
a=mid:C
m=video
a=mid:D

ie cryptex on the audio, not on the video.
If avtcodre-bundle had said "IDENTICAL", we could have rejected this offer.
As it is, rejecting it could be an interop problem.

**Comment by aboba** [comment]
I am not sure I understand why "a=cryptex" isn't session-level rather than media level. If an endpoint supports receiving and decrypting cryptex, then it should be able to handle receiving it on any m-line. The above example would most likely be a gateway that fronts a legacy video system that doesn't support cryptex. But in that scenario, why can't the gateway decrypt cryptex and pass it along to the legacy video system in cleartext?

**Comment by murillo128** [comment]
I will answer the email at AVTCORE about the IDENTICAL vs TRANSPORT, but not really sure what is the interoperability issue here.

This is my understanding:

- browsers will support receiving cryptex on all m-lines, so they will add the `cryptex` attribute on all m-lines of all bundles.
- browsers will always try to send cryptex if the other end supports cryptex (there is no api for controlling this).
- browsers will throw an exception on setRemoteDescription if the `RTCConfiguration.rtpHeaderEncryptionPolicy` is `require` and the other end does not support cryptes on any bundle.

In which case we will need to reject the SDP above? and what do we mean by "rejecting" in this case?

**Comment by alvestrand** [comment]
Seems reasonable to me.

**Comment by youennf** [comment]
The default value should probably be negotiate.

**Comment by alvestrand** [comment]
Since this is an extension, we need to consider what happens if the extension is not implemented at one end, and the extension is implemented but defaulted on the other end - also when there are middle boxes like SDP mungers that know / don't know about the extension.

In particular, the scenario:

- Application doesn't care
- Source and destination UAs implement a=cryptex
- Middle box (SFU, for instance) doesn't know about a=cryptex, passes all unknown SDP options blindly
- Middle box depends on reading RTP header extensions (like audio volume)

If the default is "negotiate", header extensions will be encrypted, and hidden from the SFU, despite neither app desiring to hide them.

I think the default (the interpretation when no configuration is given) needs to be "off", unfortunately.

**Comment by lgrahl** [comment]
> SFU [...] passes all unknown SDP options blindly

Shouldn't the SFU understand all of the provided parameters, so it can distinguish between

1. things that it needs to handle itself
2. things that it can disregard as end-to-end parameters
3. things that it cannot handle that must be stripped or rejected

When and why would it be acceptable to omit 3?

I want to emphasize that we're talking about a security and data protection feature here where (presumably) the majority would benefit from it being active by default.

**Comment by alvestrand** [comment]
When UAs introduce new features, SFUs won't be instantly upgraded to recognize them.

**Comment by murillo128** [comment]
But SFUs should not blindly add new attributes that they don't understand to the SDP answer just because they happen to be on the offer, that could cause huge problems, and not only with cryptex.

**Comment by alvestrand** [comment]
Oops. I was thinking of transport relays (which may inspect, but do not modify, the SDP), not SFUs (which negotiate each leg of the connection independently).

**Comment by aboba** [comment]
Resolved by PR 106

**Comment by fippo** [comment]
I'm late to the party with a question: if this is "all or nothing" (as described in the interim slides) why do we need a transceiver-level flag whether this was negotiated?
* negotiate: the app can parse the SDP to determine if this was negotiated
* require: negotiation fails if this is not negotiated

I don't see value in https://w3c.github.io/webrtc-extensions/#rtp-header-extension-encryption-transceiver-interface
and would suggest we remove that part.

**Comment by murillo128** [comment]
I guess we have it at transceiver level because we don't have any object abstracting a bundle and cryptex is a TRANSPORT extension which will apply to all the transceivers of the same bundle. 

Regarding the `RtpHeaderEncryptionNegotiated` I think that parsing the SDP should be the last resort of an APP and we should try to provide APIs to avoid it, but not hard feelings against removing it neither.

**Comment by fippo** [comment]
Another nit:  
> if the connection's RTCRtpHeaderEncryptionPolicy is require and the description does not support [RFC9335]

is a bit vague, might need to be clarified that cryptex is
1/ at session level and / or
2/ present for all RTP-based "m=" sections (borrowed from the RFC)

**Comment by fippo** [comment]
while we are bikeshedding anyway: the W3C text doesn't mention contributing sources but that part should be highly relevant to @henbos interests!

**Comment by sirzooro** [comment]
> Another nit:
> 
> > if the connection's RTCRtpHeaderEncryptionPolicy is require and the description does not support [RFC9335]
> 
> is a bit vague, might need to be clarified that cryptex is 1/ at session level and / or 2/ present for all RTP-based "m=" sections (borrowed from the RFC)

This point is unclear. Discussion above was focused on media-level attribute, giving impression that this is the preferred way. However `RTCRtpHeaderEncryptionPolicy` affects whole WebRTC session, so session-level attribute seems better over media-level ones. WebRTC peer could still support media-level attribute as a fallback for interoperability with non-browser peers which needs more granular control for some reason.

**Comment by fippo** [comment]
https://mailarchive.ietf.org/arch/msg/avt/pGnete_6IqExxTERNl44_9GqVRU/
has two implications:
* we should change the definition of `require` to be "mandatory to use" (i.e. reject RTP packets that are not using cryptex). It is currently mandatory to negotiate but doesn't require rejecting RTP extensions received in clear. That should be in the spirit of the RFC
* reject modifications to rtpHeaderEncryptionPolicy in setConfiguration. This requires adding text that modifies https://w3c.github.io/webrtc-pc/#set-the-configuration step 3.

**Comment by fippo** [comment]
recapping my feedback:
1/ I don't see much value in the per-transceiver attribute but implementing it as described is possible.
2/ "supports cryptex" needs to be aligned with the RFC (editorial)
3/ CSRC encryption should be mentioned (editorial)
4/ align the definition of "require" with the RFC and reject packets that do not use cryptex.
5/ Since March 16 libsrtp changed so we can now modify it at runtime. Not something I would recommend in practice.

New ask:
- since cryptex is declarative in the SDP, i.e. one puts `a=cryptex` into the SDP to say "I support receiving this" it might be good for the rollout to have a "disabled" value. This would match the libWebRTC C++ implementation.

(can we reopen this please?)

**Comment by jan-ivar** [comment]
This issue was discussed at the [WebRTC 16 June 2026 meeting](https://www.w3.org/2026/06/16-webrtc-minutes.html#9a7b).
