### ISSUE TITLE
Suggest API for generating a Stream rather than a MediaStreamTrack from incoming media

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-extensions#85]
There's been expressed a desire to detach the codec functionality from the transport handling functionality of a PeerConnection.
This is part of the gradual process of componentizing the PeerConnection, but suggests a different slice than what had been proposed in [[ORTC]].

Suggestion:

- New event "onmedia", which contains a Stream object, as well as metadata (like media type, PT and so on) that allows identifying what the PeerConnection knows about how the incoming Stream's frame should be decoded
- If the Stream object is unlocked (has no Reader) when the event handler returns, or there is no event handler, the PeerConnection will instantiate a decoder, will create a MediaStreamTrack with the output of the decoder, and fire an "ontrack" event.
- If the Stream object is locked when the event handler returns, the PeerConnection will not instantiate a decoder, will not create a track, and will not fire an "ontrack" event. Instead, it will push EncodedAudioFrames or EncodedVideoFrames as appropriate onto the Stream object; these will be pushed as soon as they are assembled, without regard to RTP sequence numbers. The sequence numbers will be available as metadata.

Input sought on whether this seems to make sense, or if it has some glaring deficencies compared to present APIs.

**Comment by rshpount** [comment]
In this mode, Stream object Reader should be responsible initial and subsequent for codec re-negotiation. So, Reader should get the offer description from the Stream and provide the answer. The Reader should also have an interface to handle re-negotiation.

Also, how would this deal with lip-sync across multiple tracks? You need a way to specify that several decoders are grouped. This can be a decoder implementation detail, but the Stream object should reference other related streams.

Finally, would it be possible to only use the new interface on some of the tracks, such as custom decoder for audio and browser decoder for video? Would we need to expose browser-level decoders so that it would be possible to implement the lip sync?

**Comment by rshpount** [comment]
The control surface with SetParameters with "codecs" might be unnecessarily limited. If support for custom decoders is added, it should be possible to define custom codecs, which means it would be needed to create custom RTCRtpCodecParameters instead of just selecting from a pre-defined set. It should also be possible to modify sdpFmtpLine in the answer or add custom codecs not present in the offer.

When dealing with regular tracks, adding multiple tracks to the same MediaStream should result in sending them as a part of the same lipsync group. Since there are no tracks in this proposal some other way of specifying this is needed.
